"use client";

import Link from "next/link";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Menu, X } from "lucide-react";

const navLinks = [
  { href: "/", label: "Anasayfa" },
    { href: "/hakkimizda", label: "Hakkımızda" },
      { href: "/blog", label: "Blog" },
        { href: "/iletisim", label: "İletişim" },
        ];

        export function Header() {
          const [isOpen, setIsOpen] = useState(false);

            return (
                <header className="sticky top-0 z-50 bg-white/95 backdrop-blur-md border-b border-gray-100 shadow-sm">
                      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                              <div className="flex items-center justify-between h-16">
                                        <Link href="/" className="flex items-center gap-2">
                                                    <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
                                                                  <span className="text-white font-bold text-sm">P</span>
                                                                              </div>
                                                                                          <span className="text-xl font-bold text-gray-900">
                                                                                                        Pilates<span className="text-primary">Topu</span>
                                                                                                                    </span>
                                                                                                                              </Link>

                                                                                                                                        <nav className="hidden md:flex items-center gap-8">
                                                                                                                                                    {navLinks.map((link) => (
                                                                                                                                                                  <Link
                                                                                                                                                                                  key={link.href}
                                                                                                                                                                                                  href={link.href}
                                                                                                                                                                                                                  className="text-gray-600 hover:text-primary transition-colors font-medium text-sm"
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                {link.label}
                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                    href="/is-ortakligi"
                                                                                                                                                                                                                                                                                                                  className="bg-primary hover:bg-primary-700 text-white px-5 py-2 rounded-full text-sm font-semibold transition-all hover:shadow-lg"
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                            İşletmenizi Ekleyin
                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                  </nav>

                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                        className="md:hidden p-2"
                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setIsOpen(!isOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                aria-label="Menü"
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                      {isOpen ? <X size={24} /> : <Menu size={24} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initial={{ opacity: 0, height: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              animate={{ opacity: 1, height: "auto" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          exit={{ opacity: 0, height: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="md:hidden bg-white border-t"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="px-4 py-4 space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {navLinks.map((link) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={link.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href={link.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="block text-gray-700 hover:text-primary py-2 font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {link.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="/is-ortakligi"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="block bg-primary text-white px-5 py-2.5 rounded-full text-center font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => setIsOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              İşletmenizi Ekleyin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }