import Link from "next/link";
import { Mail, Phone, MapPin } from "lucide-react";
import { cities } from "@/lib/data/cities";

export function Footer() {
  const popularCities = cities.slice(0, 20);

    return (
        <footer className="bg-gray-900 text-gray-300">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10">
                                <div>
                                            <Link href="/" className="flex items-center gap-2 mb-4">
                                                          <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
                                                                          <span className="text-white font-bold text-sm">P</span>
                                                                                        </div>
                                                                                                      <span className="text-xl font-bold text-white">
                                                                                                                      Pilates<span className="text-primary-300">Topu</span>
                                                                                                                                    </span>
                                                                                                                                                </Link>
                                                                                                                                                            <p className="text-sm text-gray-400 leading-relaxed">
                                                                                                                                                                          Türkiye&apos;nin pilates haritası. Sana en yakın stüdyoları, yorumları ve uzmanlık alanlarını tek bir yerde keşfet.
                                                                                                                                                                                      </p>
                                                                                                                                                                                                </div>

                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                      <h3 className="font-semibold text-white mb-4">Platform</h3>
                                                                                                                                                                                                                                  <ul className="space-y-2 text-sm">
                                                                                                                                                                                                                                                <li><Link href="/hakkimizda" className="hover:text-primary-300 transition">Hakkımızda</Link></li>
                                                                                                                                                                                                                                                              <li><Link href="/blog" className="hover:text-primary-300 transition">Blog</Link></li>
                                                                                                                                                                                                                                                                            <li><Link href="/iletisim" className="hover:text-primary-300 transition">İletişim</Link></li>
                                                                                                                                                                                                                                                                                          <li><Link href="/is-ortakligi" className="hover:text-primary-300 transition">İşletmenizi Ekleyin</Link></li>
                                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                      <h3 className="font-semibold text-white mb-4">Yasal</h3>
                                                                                                                                                                                                                                                                                                                                                  <ul className="space-y-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                <li><Link href="/kullanim-kosullari" className="hover:text-primary-300 transition">Kullanım Koşulları</Link></li>
                                                                                                                                                                                                                                                                                                                                                                              <li><Link href="/gizlilik-politikasi" className="hover:text-primary-300 transition">Gizlilik Politikası</Link></li>
                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold text-white mb-4">Bize Ulaşın</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <ul className="space-y-3 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Mail size={16} className="text-primary-300" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="mailto:info@pilatestopu.com" className="hover:text-primary-300 transition">info@pilatestopu.com</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Phone size={16} className="text-primary-300" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="tel:+905446732202" className="hover:text-primary-300 transition">+90 544 673 22 02</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li className="flex items-start gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <MapPin size={16} className="text-primary-300 mt-0.5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>Fatih, İstanbul</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-12 pt-8 border-t border-gray-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold text-white mb-4">Şehirlere Göre Pilates Salonları</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-2 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {popularCities.map((city) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link key={city.slug} href={`/${city.slug}`} className="hover:text-primary-300 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {city.name} Pilates
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-8 pt-8 border-t border-gray-800 text-center text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>&copy; 2019-{new Date().getFullYear()} PilatesTopu. Tüm hakları saklıdır.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }